export const RECOVERY_STRATEGY = {
  RETRY_PAYMENT: "RETRY_PAYMENT",
  RETRY_MANDATE: "RETRY_MANDATE",
  SEND_PAYMENT_LINK: "SEND_PAYMENT_LINK",
  SEND_EMAIL: "SEND_EMAIL",
  SEND_WHATSAPP: "SEND_WHATSAPP",
  VOICE_RECOVERY: "VOICE_RECOVERY",
  SUBSCRIPTION_RETRY: "SUBSCRIPTION_RETRY",
  PAYMENT_REMINDER: "PAYMENT_REMINDER",
  B2B_CHASER: "B2B_CHASER",
  PROMISE_TO_PAY: "PROMISE_TO_PAY",
  ESCALATE: "ESCALATE",
  NO_ACTION: "NO_ACTION",
} as const;

export type RecoveryStrategy =
  (typeof RECOVERY_STRATEGY)[keyof typeof RECOVERY_STRATEGY];

export const RECOVERY_CASE_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  RECOVERED: "RECOVERED",
  PARTIALLY_RECOVERED: "PARTIALLY_RECOVERED",
  FAILED: "FAILED",
  STOPPED: "STOPPED",
  EXPIRED: "EXPIRED",
} as const;

export type RecoveryCaseStatus =
  (typeof RECOVERY_CASE_STATUS)[keyof typeof RECOVERY_CASE_STATUS];

export const RECOVERY_ACTION_TYPE = {
  RETRY_PAYMENT: "RETRY_PAYMENT",
  RETRY_MANDATE: "RETRY_MANDATE",
  SEND_EMAIL: "SEND_EMAIL",
  SEND_WHATSAPP: "SEND_WHATSAPP",
  SEND_SMS: "SEND_SMS",
  VOICE_CALL: "VOICE_CALL",
  SEND_PAYMENT_LINK: "SEND_PAYMENT_LINK",
  SUBSCRIPTION_RETRY: "SUBSCRIPTION_RETRY",
  PAYMENT_REMINDER: "PAYMENT_REMINDER",
  ESCALATE: "ESCALATE",
} as const;

export type RecoveryActionType =
  (typeof RECOVERY_ACTION_TYPE)[keyof typeof RECOVERY_ACTION_TYPE];

export const RECOVERY_CHANNEL = {
  PAYMENT_API: "PAYMENT_API",
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
  SMS: "SMS",
  VOICE: "VOICE",
  DASHBOARD: "DASHBOARD",
} as const;

export type RecoveryChannel =
  (typeof RECOVERY_CHANNEL)[keyof typeof RECOVERY_CHANNEL];

export const ACTION_STATUS = {
  SCHEDULED: "SCHEDULED",
  EXECUTING: "EXECUTING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
  CANCELLED: "CANCELLED",
} as const;

export type ActionStatus =
  (typeof ACTION_STATUS)[keyof typeof ACTION_STATUS];

export const ATTEMPT_STATUS = {
  STARTED: "STARTED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  TIMEOUT: "TIMEOUT",
  CANCELLED: "CANCELLED",
} as const;

export type AttemptStatus =
  (typeof ATTEMPT_STATUS)[keyof typeof ATTEMPT_STATUS];

export const DECISION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  BLOCKED: "BLOCKED",
  EXECUTED: "EXECUTED",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
} as const;

export type DecisionStatus =
  (typeof DECISION_STATUS)[keyof typeof DECISION_STATUS];

export const POLICY_RESULT = {
  ALLOWED: "ALLOWED",
  BLOCKED: "BLOCKED",
  ESCALATED: "ESCALATED",
} as const;

export type PolicyResult =
  (typeof POLICY_RESULT)[keyof typeof POLICY_RESULT];

export const VERIFICATION_TYPE = {
  PAYMENT_STATUS: "PAYMENT_STATUS",
  RAZORPAY_WEBHOOK: "RAZORPAY_WEBHOOK",
  TRANSACTION_LOOKUP: "TRANSACTION_LOOKUP",
  MANUAL: "MANUAL",
} as const;

export type VerificationType =
  (typeof VERIFICATION_TYPE)[keyof typeof VERIFICATION_TYPE];

export const VERIFICATION_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
} as const;

export type VerificationStatus =
  (typeof VERIFICATION_STATUS)[keyof typeof VERIFICATION_STATUS];

export const ATTRIBUTION_TYPE = {
  DIRECT: "DIRECT",
  ASSISTED: "ASSISTED",
  PROBABILISTIC: "PROBABILISTIC",
} as const;

export type AttributionType =
  (typeof ATTRIBUTION_TYPE)[keyof typeof ATTRIBUTION_TYPE];