export const REVENUE_EVENT = {
  CHECKOUT_ABANDONMENT: {
    DETECTION_WINDOW_MINUTES: 30,
  },

  PAYMENT_FAILURE: {
    MAX_RECENT_FAILURES_FOR_ESCALATION: 3,
  },

  PAYMENT_DEGRADATION: {
    MIN_FAILURE_RATE_PERCENT: 20,
    MIN_SAMPLE_SIZE: 20,
  },

  INVOICE_OVERDUE: {
    FIRST_REMINDER_AFTER_DAYS: 1,
  },
} as const;