export const POLICY = {
  LIMITS: {
    MAX_RETRIES_HARD_LIMIT: 5,
    MAX_COMMUNICATION_ATTEMPTS_HARD_LIMIT: 5,
    MAX_RECOVERY_ACTIONS_HARD_LIMIT: 10,
  },

  WINDOWS: {
    MAX_RETRY_WINDOW_HOURS: 168,
    MAX_RECOVERY_WINDOW_HOURS: 336, 
  },

  VOICE: {
    MAX_ATTEMPTS: 2,
    MAX_CALL_DURATION_SECONDS: 300,
  },

  ESCALATION: {
    MAX_AUTO_ESCALATIONS: 3,
  },
} as const;