export const RECOVERY = {
  RETRY: {
    DEFAULT_MAX_ATTEMPTS: 3,
    DEFAULT_RETRY_WINDOW_HOURS: 72,
    MIN_RETRY_INTERVAL_MINUTES: 30,
  },

  COMMUNICATION: {
    DEFAULT_MAX_ATTEMPTS: 3,
    MIN_INTERVAL_HOURS: 6,
  },

  ESCALATION: {
    DEFAULT_THRESHOLD: 3,
  },

  ACTION: {
    EXECUTION_TIMEOUT_MS: 30_000,
    VERIFICATION_TIMEOUT_MS: 60_000,
  },

  STOP: {
    MAX_TOTAL_ACTIONS: 5,
  },
} as const;