export const MERCHANT_DEFAULTS = {
  CURRENCY: "INR",

  MAX_RETRIES: 3,
  RETRY_WINDOW_HOURS: 72,
  MAX_COMMUNICATION_ATTEMPTS: 3,
  ALLOW_AUTO_RETRY: false,
  ALLOW_VOICE_RECOVERY: false,
  ESCALATION_THRESHOLD: 3,
  POLICY_ACTIVE: true,
} as const;

export const MERCHANT_LIMITS = {
  MIN_RETRIES: 0,
  MAX_RETRIES: 10,

  MIN_RETRY_WINDOW_HOURS: 1,
  MAX_RETRY_WINDOW_HOURS: 720,

  MIN_COMMUNICATION_ATTEMPTS: 0,
  MAX_COMMUNICATION_ATTEMPTS: 20,

  MIN_ESCALATION_THRESHOLD: 1,
  MAX_ESCALATION_THRESHOLD: 20,
} as const;

export const MERCHANT_CURRENCY = {
  INR: "INR",
} as const;

export const MERCHANT_POLICY = {
  DEFAULT_NAME: "Default Recovery Policy",
} as const;