export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",

  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  MERCHANT_INACTIVE: "MERCHANT_INACTIVE",

  RAZORPAY_CONNECTION_FAILED: "RAZORPAY_CONNECTION_FAILED",
  RAZORPAY_AUTH_FAILED: "RAZORPAY_AUTH_FAILED",
  RAZORPAY_API_ERROR: "RAZORPAY_API_ERROR",
  RAZORPAY_RATE_LIMITED: "RAZORPAY_RATE_LIMITED",
  RAZORPAY_WEBHOOK_INVALID: "RAZORPAY_WEBHOOK_INVALID",

  INVALID_REVENUE_EVENT: "INVALID_REVENUE_EVENT",
  EVENT_ALREADY_PROCESSED: "EVENT_ALREADY_PROCESSED",
  EVENT_PROCESSING_FAILED: "EVENT_PROCESSING_FAILED",

  RISK_ANALYSIS_FAILED: "RISK_ANALYSIS_FAILED",
  INSUFFICIENT_RISK_DATA: "INSUFFICIENT_RISK_DATA",

  RECOVERY_CASE_NOT_FOUND: "RECOVERY_CASE_NOT_FOUND",
  RECOVERY_NOT_ELIGIBLE: "RECOVERY_NOT_ELIGIBLE",
  RECOVERY_ALREADY_COMPLETED: "RECOVERY_ALREADY_COMPLETED",
  RECOVERY_EXPIRED: "RECOVERY_EXPIRED",
  RECOVERY_STOPPED: "RECOVERY_STOPPED",

  POLICY_VIOLATION: "POLICY_VIOLATION",
  RETRY_LIMIT_EXCEEDED: "RETRY_LIMIT_EXCEEDED",
  COMMUNICATION_LIMIT_EXCEEDED: "COMMUNICATION_LIMIT_EXCEEDED",
  RECOVERY_ACTION_LIMIT_EXCEEDED: "RECOVERY_ACTION_LIMIT_EXCEEDED",

  ACTION_NOT_ALLOWED: "ACTION_NOT_ALLOWED",
  ACTION_EXECUTION_FAILED: "ACTION_EXECUTION_FAILED",
  ACTION_TIMEOUT: "ACTION_TIMEOUT",

  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  RECOVERY_NOT_CONFIRMED: "RECOVERY_NOT_CONFIRMED",

  VOICE_CALL_FAILED: "VOICE_CALL_FAILED",
  VOICE_CALL_LIMIT_EXCEEDED: "VOICE_CALL_LIMIT_EXCEEDED",
  PROMISE_TO_PAY_INVALID: "PROMISE_TO_PAY_INVALID",
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];