export const EVENT_VERSION = "v1" as const;

export type EventVersion = typeof EVENT_VERSION;

export const EVENT_SOURCE = {
  RAZORPAY: "RAZORPAY",
  API: "API",
  WORKER: "WORKER",
  SYSTEM: "SYSTEM",
} as const;

export type EventSource =
  (typeof EVENT_SOURCE)[keyof typeof EVENT_SOURCE];

export const EVENT_TYPE = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_AUTHORIZED: "PAYMENT_AUTHORIZED",
  PAYMENT_CAPTURED: "PAYMENT_CAPTURED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",

  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_CHARGED: "SUBSCRIPTION_CHARGED",
  SUBSCRIPTION_FAILED: "SUBSCRIPTION_FAILED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",

  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_ISSUED: "INVOICE_ISSUED",
  INVOICE_PAID: "INVOICE_PAID",
  INVOICE_OVERDUE: "INVOICE_OVERDUE",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",

  WEBHOOK_RECEIVED: "WEBHOOK_RECEIVED",
} as const;

export type EventType =
  (typeof EVENT_TYPE)[keyof typeof EVENT_TYPE];

export const EVENT_STATUS = {
  RECEIVED: "RECEIVED",
  PROCESSING: "PROCESSING",
  PROCESSED: "PROCESSED",
  FAILED: "FAILED",
  IGNORED: "IGNORED",
} as const;

export type EventStatus =
  (typeof EVENT_STATUS)[keyof typeof EVENT_STATUS];