export const DETECTION_RULES = {
  PAYMENT_FAILED: "FAILED_PAYMENT",

  SUBSCRIPTION_FAILED: "FAILED_SUBSCRIPTION",

  SUBSCRIPTION_CHARGE_FAILED:
    "FAILED_SUBSCRIPTION",

  INVOICE_OVERDUE:
    "OVERDUE_INVOICE",

  CHECKOUT_ABANDONED:
    "CHECKOUT_ABANDONMENT",

  PAYMENT_DEGRADED:
    "PAYMENT_DEGRADATION",

  MANDATE_FAILED:
    "MANDATE_FAILURE",

  PAYMENT_LINK_EXPIRED:
    "PAYMENT_LINK_EXPIRY",
};