export const DETECTION_THRESHOLDS = {
  PAYMENT_DEGRADATION: {
    FAILURE_RATE: 0.2,
    LATENCY_MS: 3000,
    MIN_SAMPLE_SIZE: 10,
  },

  FAILED_PAYMENT: {
    DEFAULT_PROBABILITY: 0.5,
  },

  FAILED_SUBSCRIPTION: {
    DEFAULT_PROBABILITY: 0.7,
  },

  OVERDUE_INVOICE: {
    DEFAULT_PROBABILITY: 0.6,
  },

  CHECKOUT_ABANDONMENT: {
    DEFAULT_PROBABILITY: 0.5,
  },

  MANDATE_FAILURE: {
    DEFAULT_PROBABILITY: 0.7,
  },

  PAYMENT_LINK_EXPIRY: {
    DEFAULT_PROBABILITY: 0.5,
  },
};